"""Generate compact CSS named colors from a pinned, checked-in TSV snapshot.

No packages or network are needed. --check verifies generated Rust data.
--import-html PATH imports the named-color table from the cited W3C snapshot.
"""

import argparse
import hashlib
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "crates/op_css/data/named-colors.tsv"
OUTPUT = ROOT / "crates/op_css/src/named/data.rs"
SPEC = "https://www.w3.org/TR/2026/CRD-css-color-4-20260930/#named-colors"


def validate(entries):
    if len(entries) != 148 or len(set(entries.values())) != 139:
        raise ValueError("Expected 148 names and 139 distinct opaque sRGB colors")
    for name, color in entries.items():
        if not re.fullmatch(r"[a-z]{1,20}", name) or not 0 <= color <= 0xFFFFFF:
            raise ValueError(f"Invalid named color: {name}")
    for left, right in [("aqua", "cyan"), ("fuchsia", "magenta")]:
        if entries[left] != entries[right]:
            raise ValueError(f"Alias mismatch: {left}, {right}")
    for name in entries:
        if "grey" in name and entries[name] != entries[name.replace("grey", "gray")]:
            raise ValueError(f"Gray alias mismatch: {name}")


def import_html(path):
    raw = path.read_bytes()
    html = raw.decode("utf-8")
    table = re.search(r'<table class="named-color-table">(.*?)</table>', html, re.S)
    if not table:
        raise ValueError("W3C named-color table not found")
    entries = {}
    for row in re.split(r"<tr\b[^>]*>", table[1]):
        name = re.search(r'id="valdef-color-([a-z]+)"', row)
        if not name:
            continue
        colors = re.findall(r"(?:background:|<td>)#([a-f0-9]{6})", row)
        decimal = re.search(r"<td>\s*(\d+)\s+(\d+)\s+(\d+)", row)
        if len(colors) != 2 or colors[0] != colors[1] or not decimal:
            raise ValueError(f"Malformed color row: {name[1]}")
        channels = tuple(int(value) for value in decimal.groups())
        if any(value > 255 for value in channels):
            raise ValueError(f"Invalid decimal channels: {name[1]}")
        color = int(colors[0], 16)
        if channels != (color >> 16, (color >> 8) & 255, color & 255):
            raise ValueError(f"Hex/decimal mismatch: {name[1]}")
        if name[1] in entries:
            raise ValueError(f"Duplicate name: {name[1]}")
        entries[name[1]] = color
    validate(entries)
    SOURCE.parent.mkdir(parents=True, exist_ok=True)
    lines = [f"# Source: {SPEC}", f"# HTML SHA-256: {hashlib.sha256(raw).hexdigest()}"]
    lines.extend(f"{name}\t{color:06x}" for name, color in sorted(entries.items()))
    SOURCE.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def load():
    entries = {}
    for line in SOURCE.read_text(encoding="utf-8").splitlines():
        if not line or line.startswith("#"):
            continue
        name, color = line.split("\t")
        if name in entries or not re.fullmatch(r"[a-f0-9]{6}", color):
            raise ValueError(f"Malformed TSV row: {line}")
        entries[name] = int(color, 16)
    validate(entries)
    return sorted(entries.items())


def generate(entries):
    chunks = [""]
    records = []
    offset = 0
    for name, color in entries:
        if len(chunks[-1]) + len(name) > 80:
            chunks.append("")
        chunks[-1] += name
        records.append(f"    Entry::new({offset}, {len(name)}, [{color >> 16}, {(color >> 8) & 255}, {color & 255}]),")
        offset += len(name)
    if offset > 65535:
        raise ValueError("Name offsets exceed u16")
    digest = hashlib.sha256(SOURCE.read_bytes()).hexdigest()
    lines = ["// Generated by tools/generate_css_named_colors.py; do not edit.", f"// TSV SHA-256: {digest}", "", "use super::Entry;", "", "pub(super) const NAMES: &str = concat!("]
    lines.extend(f'    "{chunk}",' for chunk in chunks)
    lines.extend([");", "", "pub(super) const ENTRIES: &[Entry] = &["])
    lines.extend(records)
    lines.extend(["];", ""])
    return "\n".join(lines), offset


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--import-html", type=Path)
    args = parser.parse_args()
    if args.check and args.import_html:
        parser.error("--check and --import-html cannot be combined")
    if args.import_html:
        import_html(args.import_html)
    entries = load()
    output, name_bytes = generate(entries)
    if args.check:
        if OUTPUT.read_text(encoding="utf-8") != output:
            raise SystemExit("Generated CSS named colors differ; run the generator")
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(output, encoding="utf-8", newline="\n")
    print(f"{len(entries)} names; {name_bytes} name bytes + {len(entries) * 6} record bytes")


if __name__ == "__main__":
    main()
