"""Generate the compact Rust named-reference table from the pinned WHATWG data.

No packages or network are needed. --check verifies the checked-in output.
--import-json PATH normalizes a manually downloaded WHATWG entities.json snapshot.
"""

import argparse
import hashlib
import json
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "crates/op_html/data/entities.tsv"
OUTPUT = ROOT / "crates/op_html/src/references/named.rs"


def validate(entries):
    if len(entries) != 2231 or len([n for n in entries if n.endswith(";")]) != 2125:
        raise ValueError("Expected 2125 canonical names and 106 legacy spellings")
    for name, points in entries.items():
        if not re.fullmatch(r"&[A-Za-z0-9]+;?", name):
            raise ValueError(f"Invalid name: {name}")
        if not 1 <= len(points) <= 2 or any(
            p == 0 or p > 0x10FFFF or 0xD800 <= p <= 0xDFFF for p in points
        ):
            raise ValueError(f"Invalid replacement: {name}")
        if not name.endswith(";") and entries.get(name + ";") != points:
            raise ValueError(f"Legacy spelling disagrees with canonical entry: {name}")


def import_json(path):
    raw = path.read_bytes()
    data = json.loads(raw)
    entries = {name: item["codepoints"] for name, item in data.items()}
    validate(entries)
    for name, item in data.items():
        if item["characters"] != "".join(map(chr, entries[name])):
            raise ValueError(f"Codepoints and characters disagree: {name}")
    header = (
        "# WHATWG HTML named character references, normalized from entities.json\n"
        "# Source: https://html.spec.whatwg.org/entities.json\n"
        f"# Source SHA-256: {hashlib.sha256(raw).hexdigest()}\n"
        "# Copyright WHATWG (Apple, Google, Mozilla, Microsoft).\n"
        "# BSD-3-Clause for incorporation into source code; see third_party/WHATWG-HTML-LICENSE.txt.\n"
        "# Format: exact source spelling<TAB>Unicode codepoints (hex, space separated)\n"
    )
    rows = [name + "\t" + " ".join(f"{p:X}" for p in entries[name]) for name in sorted(entries)]
    SOURCE.parent.mkdir(parents=True, exist_ok=True)
    SOURCE.write_text(header + "\n".join(rows) + "\n", encoding="utf-8", newline="\n")


def read_entries():
    entries = {}
    for line in SOURCE.read_text(encoding="utf-8").splitlines():
        if not line or line.startswith("#"):
            continue
        name, points = line.split("\t")
        if name in entries:
            raise ValueError(f"Duplicate source spelling: {name}")
        entries[name] = [int(p, 16) for p in points.split()]
    validate(entries)
    return entries


def generate(entries):
    names = ""
    values = b""
    offsets = {}
    records = []
    for key in sorted((n for n in entries if n.endswith(";")), key=lambda n: n[1:-1]):
        name = key[1:-1]
        value = "".join(map(chr, entries[key])).encode("utf-8")
        if value not in offsets:
            offsets[value] = len(values)
            values += value
        records.append((len(names), offsets[value], len(name), len(value), key[:-1] in entries))
        names += name
    if len(names) > 65535 or len(values) > 65535 or max(r[2] for r in records) > 255:
        raise ValueError("Table exceeds the packed offset/length representation")
    lines = [
        "// @generated by tools/generate_html_entities.py; do not edit by hand.",
        "// Source: https://html.spec.whatwg.org/entities.json (pinned data/entities.tsv).",
        "// Copyright WHATWG (Apple, Google, Mozilla, Microsoft). BSD-3-Clause;",
        "// see third_party/WHATWG-HTML-LICENSE.txt. Representation changed, mappings preserved.",
        "use super::NamedEntry;",
        "",
        f"pub(super) const MAX_NAME_LEN: usize = {max(r[2] for r in records)};",
        "",
        "pub(super) const NAMES: &str = concat!(",
    ]
    lines += [f'    "{names[i:i+96]}",' for i in range(0, len(names), 96)]
    lines += [");", "", "pub(super) const VALUES: &str = concat!("]
    chars = values.decode("utf-8")
    for start in range(0, len(chars), 16):
        escaped = "".join("\\u{" + f"{ord(ch):x}" + "}" for ch in chars[start:start+16])
        lines.append(f'    "{escaped}",')
    lines += [");", "", "#[rustfmt::skip]", "pub(super) const ENTRIES: &[NamedEntry] = &["]
    for a, b, c, d, legacy in records:
        lines.append(f"    NamedEntry({a}, {b}, {c}, {d}, {str(legacy).lower()}),")
    lines += ["];", ""]
    print(f"{len(records)} names, {len(entries)-len(records)} legacy spellings, "
          f"{len(names)+len(values)+8*len(records):,} bytes of static table data")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--import-json", type=Path)
    args = parser.parse_args()
    if args.import_json:
        if args.check:
            parser.error("--import-json cannot be combined with --check")
        import_json(args.import_json)
    output = generate(read_entries())
    if args.check:
        if OUTPUT.read_text(encoding="utf-8") != output:
            raise SystemExit("Generated table is stale; run python tools/generate_html_entities.py")
        print("Generated table is current")
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(output, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
